PCB: false
batchsize: 32
color_jitter: false
data_dir: ../Market/pytorch
droprate: 0.5
erasing_p: 0
fp16: true
gpu_ids: '0'
lr: 0.05
name: fp16
nclasses: 751
stride: 2
train_all: true
use_dense: false
